apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: changeme
    jsonData:
      index: "logs-*"
      timeField: "@timestamp"
      esVersion: "8.0.0"

  - name: Elasticsearch-Anomalies
    type: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: changeme
    jsonData:
      index: "anomalies-*"
      timeField: "timestamp"
      esVersion: "8.0.0"

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
