filebeat.inputs:

# ========== System Logs ============

# - type: filestream
#   id: my-filestream-id
#   enabled: false
#   paths:
#     - /var/log/*.log

- type: log
  enabled: true
  paths:
    - /var/log/syslog
  tags: ["syslog"]

- type: log
  enabled: true
  paths:
    - /var/log/auth.log
  tags: ["authlog"]

- type: log
  enabled: true
  paths:
    - /var/log/kern.log
  tags: ["kernlog"]

- type: log
  enabled: true
  paths:
    - /var/log/audit/audit.log
  tags: ["auditd"]

- type: log
  enabled: true
  paths:
    - /var/log/dpkg.log
  tags: ["dpkglog"]

- type: log
  enabled: true
  paths:
    - /var/log/faillog
    - /var/log/btmp
    - /var/log/wtmp
  tags: ["login-attempts"]

- type: log
  enabled: true
  paths:
    - /var/log/ufw.log
  tags: ["firewall"]

# ========== Application Logs ============
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  tags: ["nginx"]

# =============================================

output.kafka:
  enabled: true
  hosts: ["localhost:9092"]
  topic: "system-logs"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
    #  compression: gzip
  codec.json:
    pretty: false