[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    warn

[INPUT]
    Name              tail
    Path              /var/log/auth.log,/var/log/syslog
    Tag               system.logs
    Refresh_Interval  5
    Skip_Long_Lines   On

[FILTER]
    Name   grep
    Match  system.logs
    Exclude log .*fluent-bit.*

[FILTER]
    Name         record_modifier
    Match        system.logs
    Record       hostname ${HOSTNAME}

[OUTPUT]
    Name        kafka
    Match       system.logs
    Brokers     ${KAFKA_HOST}:9092
    Topics      raw-logs
    Timestamp_Key @timestamp
    Retry_Limit 3
